version: "3.9"

services:
  gallery-react:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 30s
      update_config:
        order: start-first
    ports:
      - "5001:8080"
    environment:
      PORT: 8080
